### ISSUE TITLE
Trabajo Final PV Avances

### ISSUE THREAD

**Issue by gustso** [GastonCuevas/Proyecto_Jugueteria#1]
Avances Aprobados
Se encuentran mapeadas todas las clases del dominio
Sin embargo no se observa la participacion de Ruarte ni Anze, ni su incoporacion al proyecto.
Solo commit de @GastonCuevas . Falta participacion de  @CarlosTorres99 .
Se debe mejorar

**Comment by gustso** [comment]
Estimados.
Se ve un avance con el proyecto, sin embargo NO se ve trabajo grupal.

Chequear la siguiente lista.
1.- Logín funciona?
2.- Redirije a las páginas de cliente y de administrador?
3.- En la página principal hay un link a otra página para crear un usuario de tipo cliente? Lo crea correctamente? (aquí se crea el usuario y el cliente simultaneamente)
4.- En la página de administrador de muestra listado de usuarios?
5.- En la página de administrador se puede crear usuarios con distintos tipos de roles (clientes o administradores)?
6.- En la página de administrador se muestran los productos? se pueden crear productos?
7.- En la página de administrador se muestran las categorias? se pueden crear categorias de productos?
8.- En la página de cliente se muestran los productos?

Hasta allí la tarea de la semana pasada.
Ahora se debería agregar en la página de clientes un botón que permita agregar los productos al carrito de compras, luego de indicar la cantidad de productos se debe confirmar la compra, cuando se confirma la compra se debe elegir el medio de pago y finalmente comprar.
Al final se pedirá que se imprima la factura.

De la lista anterior, por favor ir comentando qué está funcionando. Supongo que Anze ya no trabaja en este grupo. No se ha incorporado a Ruarte y también está en una situación muy complicada.
Saludos @GastonCuevas @CarlosTorres99

**Comment by GastonCuevas** [comment]
Buen día Profesor, de la lista anterior funciona todo hasta el punto 5, falta programar punto 6,7 y 8.
Respecto a Ruarte Y Torres estan trabajando para completar estos 3 puntos restantes.
